### ISSUE TITLE
Code Questions

### ISSUE THREAD

**Issue by jianlai123-123** [kasvii/GATOR#1]
Hello, I have a few questions about the code, and I hope to receive your answer. First, I didn't understand where the SDGA code started. 
<img width="349" alt="121" src="https://user-images.githubusercontent.com/117512033/226554796-485296d2-9461-45cc-a2a7-c8d7b252bda2.png">

Secondly, from models import meshnet, posenet, I didn't see these two modules in models. Looking forward to your reply, thank you.
<img width="608" alt="12" src="https://user-images.githubusercontent.com/117512033/226554422-111ac532-0641-4e76-99e7-06ecc86f425c.png">
@kasvii

**Comment by kasvii** [comment]
Thank you for pointing out this. The old code was incomplete. We have collated and reuploaded the full code.
1. SDGA is [here](https://github.com/kasvii/GATOR/blob/7af1508a0913d8fb0dcffe10082a16399596e48d/lib/models/GAT.py#L16).
2. The 'meshnet' and 'posenet' were the old names of MDR and GAT, respectively. And we have corrected them.

**Comment by jianlai123-123** [comment]
Thank you for your reply.

**Comment by jianlai123-123** [comment]
Hello, what do these two sentences of code mean? 
shortest_path_result = np.load('./data/base_data/shortest_path_h36m.npy') 
 path = np.load('./data/base_data/path_h36m.npy')
        
The dataset does not contain a shortest_ path_ H36m. npy and path_ h36m.npy
<img width="420" alt="1" src="https://user-images.githubusercontent.com/117512033/227760529-562a72fc-fca8-4e95-adc9-c6f7381db179.png">
@kasvii

**Comment by kasvii** [comment]
The 'shortest path results' denotes the hop distances between joints. And the 'path' records the path information from one joint to another. [Here](https://github.com/kasvii/GATOR/blob/master/asset/hop%26path.png) shows the illustration. They are pre-processed from the skeletons, which are used to calculate the hop and path encodings. You can get them from the uploaded [base_data](https://github.com/kasvii/GATOR/blob/53a3e5a92055475d37c732d8c9e1fc89075bc5a5/README.md?plain=1#L80).

**Comment by jianlai123-123** [comment]
Thank you for your reply.

**Comment by jianlai123-123** [comment]
Hello, I have a few questions about the code and hope to receive your response. First, shortest_ path_ result = np.load('./data/base_data/shortest_path_3dpw.npy')
path = np.load('./data/base_data/path_3dpw.npy')。 base_ Two data files not mentioned in data, such as shortest_ path_ 3dpw.npy and path_ 3dpw.npy。 Do I have to handle this myself?
 Download base_ Data does not have permissions.
<img width="593" alt="2" src="https://user-images.githubusercontent.com/117512033/227834711-92255b4c-4e56-4bad-8782-5e5c426a8ced.png">

Second, calculate edge_ Input mentions edg_ Adj, but calculate edg_ Adj requires a template_ joint，J_ regressor，init_ vertices，SMPL_ MEAN_ vertices。

How to obtain J_ regressor and what does it represent
Is it obtained this way: J_ regressor = eval(f'torch.Tensor(main_dataset.joint_regressor_{cfg.DATASET.input_joint_set})') ？

Why use smpl_ mean_ Vertices.npy Calculate init_ vertices 。
I hope to receive your reply.
@kasvii

**Comment by kasvii** [comment]
1. Thank you for pointing out that. The download permission is available now. And the base_data list is updated including the path files.
2. J_regressor is a transformation matrix that is multiplied by the mesh and can project the mesh to the 3D joints. For detailed information, you can refer to the Sec. 4.3 in the main paper of [Pose2Mesh](https://github.com/hongsukchoi/Pose2Mesh_RELEASE). The J_regressors are in data/COCO/J_regressor_coco.npy and data/Human36M/J_regressor_h36m_correct.npy. And you can get them by the code you mentioned.
3. 'smpl_ mean_ vertices' is used as the initialization of vertices following previous work like [GTRS](https://github.com/zczcwh/GTRS), [Mesh Graphormer](https://github.com/microsoft/MeshGraphormer), [GraphCMR](https://github.com/nkolot/GraphCMR).

**Comment by jianlai123-123** [comment]
Thank you for your reply.

**Comment by jianlai123-123** [comment]
Hello, introduce graph structure information into the attention mechanism. Will adding structural information to the attention score make the model unable to train? I found that as long as the attention score model is modified, it cannot be trained. May I ask what is going on? Looking forward to your reply, thank you.

**Comment by kasvii** [comment]
Our model has added two kinds of structural information, i.e., hop and path. And it can be trained.
If you are changing this part, you can check if the gradient is available.

**Comment by jianlai123-123** [comment]
Thank you for your reply.
