### ISSUE TITLE
Test result is weird

### ISSUE THREAD

**Issue by moonsh** [kasvii/GATOR#2]
After the below testing command, I got the evaluation but it's very different from your paper.
"python ./main/test.py --cfg ./asset/yaml/gator_cocoJ_test_human36_coco_muco_det.yml --gpu 0"

Is there something I am missing?

This is the evaluation result I got.

===> Start testing...
(550/555) => surface error: 359.7289, joint error: 297.4987: 100%|█| 555/555 [00
 MPVPE: 339.34, MPJPE: 293.37
Evaluation start...

H36M MPJPE (mm)    >> tot: 293.36
H36M PA-MPJPE (mm) >> tot: 127.48
SMPL MPJPE (mm)    >> tot: 259.53
MPVPE (mm)         >> tot: 329.88

**Comment by kasvii** [comment]
I tested it again and it's correct. Did you load the weight './results/3dpw_det.pth.tar'? Could you please provide the test log?

**Comment by moonsh** [comment]
Yes. I did it correctly.
Actually, I asked the same question to Pose2Mesh repo.

https://github.com/hongsukchoi/Pose2Mesh_RELEASE/issues/63

He told me he changed the 3dpw annotation file recently.
Can you share the previous annotation file so I can try ?

**Comment by kasvii** [comment]
I see. I have uploaded the previous annotation file of 3DPW [here](https://drive.google.com/drive/folders/1Sw9HB1nbMYHP2hX1TeoQd-groUMb2HIo?usp=sharing) and changed the counterpart in README.

**Comment by moonsh** [comment]
Thank you. It works great now!
